name: dtls2
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-131.0.dev

# Add regular dependencies here.
dependencies:
  asn1lib: ^1.5.3
  basic_utils: ^5.7.0
  cryptography: ^2.7.0
  elliptic: ^0.3.10
  pem: ^2.0.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
